import "./env-augmentation.ts";

/**
 * Validated application configuration decoded from Workers `Env`.
 *
 * `Env` (bindings + vars + secrets) is generated by `wrangler types` and
 * augmented with secret names imported above. `readConfig` decodes the raw
 * string/secret boundaries into strongly-typed domain values so the rest of the
 * codebase never touches unvalidated env again.
 */

/** Decoded Firebase/GCP service account used to authorize Google Cloud Storage. */
export interface ServiceAccount {
  readonly projectId: string;
  readonly clientEmail: string;
  readonly privateKeyPem: string;
  readonly privateKeyId: string;
}

export interface Config {
  readonly bucket: string;
  readonly serviceAccount: ServiceAccount;
  readonly adminToken: string;
  readonly maxUploadBytes: number;
  readonly corsOrigins: Set<string>;
}

const defaultCorsOrigins = [
  "http://localhost:3000",
  "http://127.0.0.1:3000",
  "http://localhost:8787",
];

const defaultMaxUploadMb = 250;

export function readConfig(env: Env): Config {
  return {
    bucket: readNonEmpty(env.FIREBASE_STORAGE_BUCKET, "FIREBASE_STORAGE_BUCKET"),
    serviceAccount: readServiceAccount(env.FIREBASE_ACCOUNT),
    adminToken: readNonEmpty(env.ADMIN_TOKEN, "ADMIN_TOKEN"),
    maxUploadBytes: readMaxUploadBytes(env.MAX_UPLOAD_MB),
    corsOrigins: readCorsOrigins(env.CORS_ORIGINS),
  };
}

function readServiceAccount(raw: string): ServiceAccount {
  if (!raw) {
    throw new ConfigError("Brak zmiennej FIREBASE_ACCOUNT");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    throw new ConfigError(
      `FIREBASE_ACCOUNT nie jest poprawnym JSON-em (${detail}). ` +
        "Wartość musi być jednoliniowym JSON-em klucza serwisowego Firebase; " +
        "wygeneruj go przez: node -e \"process.stdout.write(JSON.stringify(require('./serviceAccountKey.json')))\"",
    );
  }
  if (!isRecord(parsed)) {
    throw new ConfigError("FIREBASE_ACCOUNT musi być obiektem JSON");
  }

  const projectId = readField(parsed, "project_id");
  const clientEmail = readField(parsed, "client_email");
  const privateKey = readField(parsed, "private_key");
  if (!projectId || !clientEmail || !privateKey) {
    throw new ConfigError("FIREBASE_ACCOUNT nie zawiera wymaganych pól");
  }

  return {
    projectId,
    clientEmail,
    privateKeyPem: privateKey.replace(/\\n/g, "\n"),
    privateKeyId: readField(parsed, "private_key_id") ?? "",
  };
}

function readField(record: Record<string, unknown>, key: string): string | undefined {
  const value = record[key];
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function readNonEmpty(value: string, name: string): string {
  if (!value) {
    throw new ConfigError(`Brak zmiennej ${name}`);
  }
  return value;
}

function readMaxUploadBytes(raw: string): number {
  const parsed = Number(raw);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    return defaultMaxUploadMb * 1024 * 1024;
  }
  return parsed * 1024 * 1024;
}

function readCorsOrigins(raw: string): Set<string> {
  const configured = raw
    .split(",")
    .map(normalizeOrigin)
    .filter((value): value is string => value !== undefined);
  return new Set([...defaultCorsOrigins, ...configured]);
}

function normalizeOrigin(value: string): string | undefined {
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    return undefined;
  }
  try {
    return new URL(trimmed).origin;
  } catch {
    return trimmed.replace(/\/+$/, "");
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Configuration failure surfaced as a tagged error at the request boundary. */
export class ConfigError extends Error {
  override readonly name = "ConfigError";
}
